twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates': app
    file_name_pattern: '*.twig'
    form_themes:
        - '@app/form/bootstrap-layout.html.twig'

when@test:
    twig:
        strict_variables: true
